name: deploy

on:
  push:
    branches:
      - docker-deploy

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            code:
              - '**.rs'
              - '**.Dockerfile'
              - 'Makefile.toml'
              - 'Cargo.lock'
              - '.github/workflows/**'
      - if: steps.changes.outputs.code == 'true'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u mosamadeeb --password-stdin
          docker build -f docker/platform.Dockerfile -t ghcr.io/mosamadeeb/profile_stack:platform .
          docker push ghcr.io/mosamadeeb/profile_stack:platform
